Char counter function
DarkJediDJ/strrvrs pull request #2
Opened 2021-10-29 10:17 UTC by DarkJediDJ

## Checklist
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No error nor warning in the console.
## New functionality:
* Added Tests for function Reverse
* Added function Reverse
* README modified 
* Added Tests for function Calculator
* Added function Calculator

2021-10-29 10:49 UTC, Hargeon requested changes

2021-10-29 12:52 UTC, Hargeon requested changes

2021-10-29 18:51 UTC, DarkJediDJ commented
> Read about semver and create a release.

Did it

2021-10-29 20:42 UTC, Hargeon approved these changes

2021-10-31 11:04 UTC, gordonBusyman commented on reverse_test.go
> +		{"Russian string", "Россия!!!", 9},
🙃

2021-10-31 11:10 UTC, gordonBusyman requested changes
Please change the test names in both cases

2021-10-31 11:10 UTC, gordonBusyman commented on reverse_test.go
> +		t.Run(fmt.Sprintf("Couldnt count chars in string: %s in case : %s", tc.text, tc.name), func(t *testing.T) {
What does it print? 
Check the signature of t.Run `func (t *T) Run(name string, f func(t *T)) bool {}` - so what is the first param?

2021-11-01 10:32 UTC, gordonBusyman requested changes
- Rename the testcases back, calculator already defined in `TestCalculator`
- Please split the files: reverse in reverse, calculator in calculator

2021-11-01 11:13 UTC, gordonBusyman reviewed
Pls move `calculator` related tests to `calculator_test` and we are gtg

2021-11-01 12:20 UTC, gordonBusyman approved these changes

2021-11-01 12:51 UTC, merged